## Pandas --Check

In pandas every change we made in the data has to be checked. For this there are different functions. Let's look briefly into them.

After reading in the data, it is always good to check that everything went well. For checking any output we can use the print() function. The challenge is that large data files might not nicely print on screen using the print() function.

In [5]:
import pandas as pd
fp = r'C:\Users\Gokul G\Desktop\WORK\GISISH\GIS-ish\data\Kanpur.csv'
data = pd.read_csv(fp,sep=',',index_col= "Month", skiprows=6, na_values=[-999.0,-999])

In [11]:
print(data)

          AOD_1640nm  AOD_1020nm  AOD_870nm  AOD_865nm  AOD_779nm  AOD_675nm  \
Month
2001-JAN         NaN    0.176252   0.224173        NaN        NaN   0.313830
2001-FEB         NaN    0.207033   0.249738        NaN        NaN   0.327059
2001-MAR         NaN    0.222493   0.249700        NaN        NaN   0.294628
2001-APR         NaN    0.317698   0.338976        NaN        NaN   0.373772
2001-MAY         NaN    0.671964   0.702189        NaN        NaN   0.752185
...              ...         ...        ...        ...        ...        ...
2022-AUG         NaN         NaN        NaN        NaN        NaN        NaN
2022-SEP         NaN         NaN        NaN        NaN        NaN        NaN
2022-OCT         NaN         NaN        NaN        NaN        NaN        NaN
2022-NOV         NaN         NaN        NaN        NaN        NaN        NaN
2022-DEC         NaN         NaN        NaN        NaN        NaN        NaN

          AOD_667nm  AOD_620nm  AOD_560nm  AOD_555nm  ...  \
Month                                                 ...
2001-JAN        NaN        NaN        NaN        NaN  ...
2001-FEB        NaN        NaN        NaN        NaN  ...
2001-MAR        NaN        NaN        NaN        NaN  ...
2001-APR        NaN        NaN        NaN        NaN  ...
2001-MAY        NaN        NaN        NaN        NaN  ...
...             ...        ...        ...        ...  ...
2022-AUG        NaN        NaN        NaN        NaN  ...
2022-SEP        NaN        NaN        NaN        NaN  ...
2022-OCT        NaN        NaN        NaN        NaN  ...
2022-NOV        NaN        NaN        NaN        NaN  ...
2022-DEC        NaN        NaN        NaN        NaN  ...

          NUM_POINTS[440-870_Angstrom_Exponent]  \
Month
2001-JAN                                    174
2001-FEB                                    988
2001-MAR                                   1169
2001-APR                                   1207
2001-MAY                                    691
...                                         ...
2022-AUG                                      0
2022-SEP                                      0
2022-OCT                                      0
2022-NOV                                      0
2022-DEC                                      0

          NUM_POINTS[380-500_Angstrom_Exponent]  \
Month
2001-JAN                                    171
2001-FEB                                    986
2001-MAR                                   1169
2001-APR                                   1207
2001-MAY                                    684
...                                         ...
2022-AUG                                      0
2022-SEP                                      0
2022-OCT                                      0
2022-NOV                                      0
2022-DEC                                      0

          NUM_POINTS[440-675_Angstrom_Exponent]  \
Month
2001-JAN                                    172
2001-FEB                                    987
2001-MAR                                   1169
2001-APR                                   1207
2001-MAY                                    691
...                                         ...
2022-AUG                                      0
2022-SEP                                      0
2022-OCT                                      0
2022-NOV                                      0
2022-DEC                                      0

          NUM_POINTS[500-870_Angstrom_Exponent]  \
Month
2001-JAN                                    174
2001-FEB                                    988
2001-MAR                                   1169
2001-APR                                   1207
2001-MAY                                    691
...                                         ...
2022-AUG                                      0
2022-SEP                                      0
2022-OCT                                      0
2022-NOV                                      0
2022-DEC                                      0

          NUM_POINTS[340-440_Angstrom_Exponent]  \
Month
2001-JAN                                    169
2001-FEB                                    976
2001-MAR                                   1165
2001-APR                                   1200
2001-MAY                                    633
...                                         ...
2022-AUG                                      0
2022-SEP                                      0
2022-OCT                                      0
2022-NOV                                      0
2022-DEC                                      0

          NUM_POINTS[440-675_Angstrom_Exponent[Polar]]  Data_Quality_Level  \
Month
2001-JAN                                             0               lev20
2001-FEB                                             0               lev20
2001-MAR                                             0               lev20
2001-APR                                             0               lev20
2001-MAY                                             0               lev20
...                                                ...                 ...
2022-AUG                                             0               lev20
2022-SEP                                             0               lev20
2022-OCT                                             0               lev20
2022-NOV                                             0               lev20
2022-DEC                                             0               lev20

          Latitude(degrees)  Longitude(degrees)  Elevation(meters)
Month
2001-JAN          26.512778           80.231639                123
2001-FEB          26.512778           80.231639                123
2001-MAR          26.512778           80.231639                123
2001-APR          26.512778           80.231639                123
2001-MAY          26.512778           80.231639                123
...                     ...                 ...                ...
2022-AUG          26.512778           80.231639                123
2022-SEP          26.512778           80.231639                123
2022-OCT          26.512778           80.231639                123
2022-NOV          26.512778           80.231639                123
2022-DEC          26.512778           80.231639                123

[264 rows x 112 columns]

To display the data more neatly just calling the data is enough. But this still includes the entire data.

In [7]:
data

,AOD_1640nm,AOD_1020nm,AOD_870nm,AOD_865nm,AOD_779nm,AOD_675nm,AOD_667nm,AOD_620nm,AOD_560nm,AOD_555nm,...,NUM_POINTS[440-870_Angstrom_Exponent],NUM_POINTS[380-500_Angstrom_Exponent],NUM_POINTS[440-675_Angstrom_Exponent],NUM_POINTS[500-870_Angstrom_Exponent],NUM_POINTS[340-440_Angstrom_Exponent],NUM_POINTS[440-675_Angstrom_Exponent[Polar]],Data_Quality_Level,Latitude(degrees),Longitude(degrees),Elevation(meters)
Month,,,,,,,,,,,,,,,,,,,,,
2001-JAN,NaN,0.176252,0.224173,NaN,NaN,0.313830,NaN,NaN,NaN,NaN,...,174,171,172,174,169,0,lev20,26.512778,80.231639,123
2001-FEB,NaN,0.207033,0.249738,NaN,NaN,0.327059,NaN,NaN,NaN,NaN,...,988,986,987,988,976,0,lev20,26.512778,80.231639,123
2001-MAR,NaN,0.222493,0.249700,NaN,NaN,0.294628,NaN,NaN,NaN,NaN,...,1169,1169,1169,1169,1165,0,lev20,26.512778,80.231639,123
2001-APR,NaN,0.317698,0.338976,NaN,NaN,0.373772,NaN,NaN,NaN,NaN,...,1207,1207,1207,1207,1200,0,lev20,26.512778,80.231639,123
2001-MAY,NaN,0.671964,0.702189,NaN,NaN,0.752185,NaN,NaN,NaN,NaN,...,691,684,691,691,633,0,lev20,26.512778,80.231639,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-AUG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,lev20,26.512778,80.231639,123
2022-SEP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,lev20,26.512778,80.231639,123
2022-OCT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,lev20,26.512778,80.231639,123
2022-NOV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,lev20,26.512778,80.231639,123
2022-DEC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,lev20,26.512778,80.231639,123

- ## head()

Compared to previous cases it might be better to look at only the top 5–10 lines of the file rather than loading the entire thing. 

In this we can use data.head() to quickly check the contents of the dataframe. This function returns the first n rows for the object based on position. It is useful for quickly testing if your object has the right type of data in it.

In [12]:
data.head()

,AOD_1640nm,AOD_1020nm,AOD_870nm,AOD_865nm,AOD_779nm,AOD_675nm,AOD_667nm,AOD_620nm,AOD_560nm,AOD_555nm,...,NUM_POINTS[440-870_Angstrom_Exponent],NUM_POINTS[380-500_Angstrom_Exponent],NUM_POINTS[440-675_Angstrom_Exponent],NUM_POINTS[500-870_Angstrom_Exponent],NUM_POINTS[340-440_Angstrom_Exponent],NUM_POINTS[440-675_Angstrom_Exponent[Polar]],Data_Quality_Level,Latitude(degrees),Longitude(degrees),Elevation(meters)
Month,,,,,,,,,,,,,,,,,,,,,
2001-JAN,NaN,0.176252,0.224173,NaN,NaN,0.313830,NaN,NaN,NaN,NaN,...,174,171,172,174,169,0,lev20,26.512778,80.231639,123
2001-FEB,NaN,0.207033,0.249738,NaN,NaN,0.327059,NaN,NaN,NaN,NaN,...,988,986,987,988,976,0,lev20,26.512778,80.231639,123
2001-MAR,NaN,0.222493,0.249700,NaN,NaN,0.294628,NaN,NaN,NaN,NaN,...,1169,1169,1169,1169,1165,0,lev20,26.512778,80.231639,123
2001-APR,NaN,0.317698,0.338976,NaN,NaN,0.373772,NaN,NaN,NaN,NaN,...,1207,1207,1207,1207,1200,0,lev20,26.512778,80.231639,123
2001-MAY,NaN,0.671964,0.702189,NaN,NaN,0.752185,NaN,NaN,NaN,NaN,...,691,684,691,691,633,0,lev20,26.512778,80.231639,123

- ## tail()

We can also check the last rows of the data using data.tail(). It is useful for quickly verifying data, for example, after sorting or appending rows. If n is larger than the number of rows, this function returns all rows.

In [13]:
data.tail()

,AOD_1640nm,AOD_1020nm,AOD_870nm,AOD_865nm,AOD_779nm,AOD_675nm,AOD_667nm,AOD_620nm,AOD_560nm,AOD_555nm,...,NUM_POINTS[440-870_Angstrom_Exponent],NUM_POINTS[380-500_Angstrom_Exponent],NUM_POINTS[440-675_Angstrom_Exponent],NUM_POINTS[500-870_Angstrom_Exponent],NUM_POINTS[340-440_Angstrom_Exponent],NUM_POINTS[440-675_Angstrom_Exponent[Polar]],Data_Quality_Level,Latitude(degrees),Longitude(degrees),Elevation(meters)
Month,,,,,,,,,,,,,,,,,,,,,
2022-AUG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,lev20,26.512778,80.231639,123
2022-SEP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,lev20,26.512778,80.231639,123
2022-OCT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,lev20,26.512778,80.231639,123
2022-NOV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,lev20,26.512778,80.231639,123
2022-DEC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,lev20,26.512778,80.231639,123